cd /home/Downloads;
mv "kmquake2_levelshots_hi.pk3" "./Game Projects/" || :
mv "lanaholics-training-camp-q3a.zip" "./Game Projects/" || :
mv "llama-gpt-master.zip" "./AI Models/" || :
mv "megamindbrian@gmail.com.ical (24).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (25).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (26).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (27).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (28).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (29).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (3).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (30)" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (30).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (31).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (32).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (33).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (34).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (35).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (36).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (37).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (38).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (39).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (4).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (40).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (41).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (42).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (43).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (44).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (45)" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (45).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (46).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (47).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (48).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (49).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (5).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (50).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (51).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (52).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (53).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (54).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (55).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (56).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (57).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (58).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (59).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (6).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (60).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (61).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (62).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (63).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (64).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (65).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (66).zip" "./Documents/" || :
mv "megamindbrian@gmail.com.ical (67).zip" "./Documents/" || :
